graph TD
    subgraph "On-Body"
        subgraph "On-Body Devices"
            PUMP(Tandem Mobi Pump)
            CGM(Dexcom G7 CGM)

            CGM ==>|"CGM data<br>(Bluetooth)"| PUMP
        end


        subgraph "iPhone"
            DEXCOM_IOS["Dexcom G7<br>iOS App"]

            TANDEM_MOBI_IOS[Tandem Mobi<br>iOS App]
            
            CGM ===>|"CGM data<br>(Phone)"| DEXCOM_IOS



            PUMP ==>|"Pump data<br>(Bluetooth)"| TANDEM_MOBI_IOS

            
            

        end

        subgraph "Apple Watch"
            DEXCOM_APPLE_WATCH["Dexcom G7<br>Direct-to-Watch"]

            CGM ===>|"CGM data<br>(Phone)"| DEXCOM_APPLE_WATCH

            DEXCOM_IOS <==>|"Sync"| DEXCOM_APPLE_WATCH

        end

    end

    subgraph Internet
        DEXCOM_SHARE[Dexcom Share]
        TANDEM_SOURCE[Tandem Source]


        DEXCOM_IOS ==>|"CGM data<br>(Cloud)"| DEXCOM_SHARE
        DEXCOM_APPLE_WATCH ==>|"CGM data<br>(Cloud)"| DEXCOM_SHARE
        TANDEM_MOBI_IOS ==>|"Pump data<br>(Cloud)"| TANDEM_SOURCE


    end

    subgraph Self-Hosted
        NIGHTSCOUT{{Nightscout}}
        TCONNECTSYNC[tconnectsync]
        click NIGHTSCOUT "https://github.com/nightscout/cgm-remote-monitor"
        click TCONNECTSYNC "https://github.com/jwoglom/tconnectsync"

        DEXCOM_SHARE ==>|CGM data upload| NIGHTSCOUT

        TANDEM_SOURCE ==>|Downloads pump data| TCONNECTSYNC
        TCONNECTSYNC ==>|Pump data upload| NIGHTSCOUT
    end

    subgraph "Other Devices"
        subgraph Laptop
            CGMBAR[CGMBar MacOS<br>status bar icon]

            click CGMBAR "https://github.com/jwoglom/cgmbar"

            NIGHTSCOUT -.-> CGMBAR
        end

        SCOUT[Scout Web UI]
        STATUSBOARD[Statusboard Widget]

        click SCOUT "https://github.com/jwoglom/scout"
        click STATUSBOARD "https://github.com/jwoglom/statusboard"

        NIGHTSCOUT -.-> SCOUT
        NIGHTSCOUT -.-> STATUSBOARD

    end
