graph TD
    subgraph "On-Body"
        subgraph "On-Body Devices"
            CGM(Dexcom G6 CGM)
            PUMP(Tandem t:slim X2 Pump)

            CGM ==>|"CGM data<br>(Bluetooth)"| PUMP
        end

        subgraph Phone
            XDRIP[xDrip App]
            TCONNECTANDROID[t:connect App]
            CONTROLX2[ControlX2 App]
            click XDRIP "http://github.com/nightscoutfoundation/xdrip"
            click CONTROLX2 "http://github.com/jwoglom/controlX2"

            CGM ===>|"CGM data<br>(Bluetooth)"| XDRIP
            

            PUMP ==>|"Pump data<br>(Bluetooth)"| TCONNECTANDROID
            PUMP <==>|"Pump data<br>and remote bolus<br>(Bluetooth)"| CONTROLX2
        end

        subgraph "Pixel Watch"
            CONTROLX2WATCH["ControlX2 Watch App"]
            CONTROLX2COMPLICATION["ControlX2 Watchface<br>Complication"]
            XDRIPCOMPLICATION["G-Watch<br>Complication"]

            click CONTROLX2WATCH "http://github.com/jwoglom/controlX2"
            click CONTROLX2COMPLICATION "http://github.com/jwoglom/controlX2"
            click XDRIPCOMPLICATION "https://play.google.com/store/apps/details?id=sk.trupici.gwatch.wear"

            XDRIP -->|"CGM data"| XDRIPCOMPLICATION

            CONTROLX2COMPLICATION -.->|Read current state| CONTROLX2WATCH
            CONTROLX2 <-->|"Pump data<br>and remote bolus<br>(Bluetooth)"| CONTROLX2WATCH
        end


        subgraph Pebble
            PEBBLE["Urchin watchface"]
            click PEBBLE "https://github.com/jwoglom/urchin-cgm"
            XDRIP -->|CGM data via<br>HTTP Web Service| PEBBLE
        end
    end

    subgraph Internet
        TCONNECTPORTAL{{t:connect Portal}}
        click TCONNECTPORTAL "https://tconnect.tandemdiabetes.com/"

        TCONNECTANDROID ==>|t:connect upload| TCONNECTPORTAL
    end

    subgraph Self-Hosted
        NIGHTSCOUT{{Nightscout}}
        TCONNECTSYNC[tconnectsync]
        click NIGHTSCOUT "https://github.com/nightscout/cgm-remote-monitor"
        click TCONNECTSYNC "https://github.com/jwoglom/tconnectsync"

        XDRIP ==>|CGM data upload| NIGHTSCOUT

        TCONNECTPORTAL ==>|Downloads pump data| TCONNECTSYNC
        TCONNECTSYNC ==>|Pump data upload| NIGHTSCOUT
    end

    subgraph "Other Devices"
        subgraph Laptop
            CGMBAR[CGMBar MacOS<br>status bar icon]

            click CGMBAR "https://github.com/jwoglom/cgmbar"

            NIGHTSCOUT -.-> CGMBAR
        end

        SCOUT[Scout Web UI]
        STATUSBOARD[Statusboard Widget]

        click SCOUT "https://github.com/jwoglom/scout"
        click STATUSBOARD "https://github.com/jwoglom/statusboard"

        NIGHTSCOUT -.-> SCOUT
        NIGHTSCOUT -.-> STATUSBOARD

    end
